name: nbsphinx_test
channels:
  - conda-forge 
  - defaults
dependencies:
  - python =3
  - numpy >= 1.8.0
  - scipy
  - cython 
  - jupyter
  - matplotlib
  - bokeh
  - holoviews
  - pandas 
  - pandas-datareader
  - snakeviz
  - memory_profiler
  - line_profiler
  - sphinx
  - sphinx-autobuild
  - sphinx_rtd_theme
  - graphviz
  - pint
  - pytest
  - nbsphinx
